version: '3.8'

services:
  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: houseui-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]  # Remove this section if no NVIDIA GPU

  # Backend proxy service
  backend-proxy:
    build: .
    container_name: houseui-backend-proxy
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - OLLAMA_ENDPOINTS=http://ollama:11434
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5173}
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:

