export interface Theme {
  id: string;
  name: string;
  description: string;
  background: string;
  cardBg: string;
  cardBorder: string;
  textPrimary: string;
  textSecondary: string;
  accent: string;
  accentHover: string;
  headerBg: string;
  inputBg: string;
  buttonBg: string;
  buttonHover: string;
}

export const themes: Record<string, Theme> = {
  dark: {
    id: 'dark',
    name: 'Dark Space',
    description: 'Deep space exploration',
    background: 'bg-gradient-to-br from-gray-900 via-gray-900 to-gray-800',
    cardBg: 'bg-gray-800/80',
    cardBorder: 'border-gray-700',
    textPrimary: 'text-white',
    textSecondary: 'text-gray-400',
    accent: 'from-blue-600 to-purple-600',
    accentHover: 'from-blue-700 to-purple-700',
    headerBg: 'bg-gray-900/95',
    inputBg: 'bg-gray-700',
    buttonBg: 'bg-gray-700',
    buttonHover: 'bg-gray-600',
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean Deep',
    description: 'Underwater adventure',
    background: 'bg-gradient-to-br from-blue-950 via-cyan-950 to-teal-900',
    cardBg: 'bg-cyan-900/80',
    cardBorder: 'border-cyan-800',
    textPrimary: 'text-cyan-50',
    textSecondary: 'text-cyan-300',
    accent: 'from-cyan-600 to-blue-600',
    accentHover: 'from-cyan-700 to-blue-700',
    headerBg: 'bg-blue-950/95',
    inputBg: 'bg-cyan-800',
    buttonBg: 'bg-cyan-800',
    buttonHover: 'bg-cyan-700',
  },
  forest: {
    id: 'forest',
    name: 'Forest Night',
    description: 'Mystical woodland',
    background: 'bg-gradient-to-br from-green-950 via-emerald-950 to-teal-900',
    cardBg: 'bg-emerald-900/80',
    cardBorder: 'border-emerald-800',
    textPrimary: 'text-emerald-50',
    textSecondary: 'text-emerald-300',
    accent: 'from-emerald-600 to-green-600',
    accentHover: 'from-emerald-700 to-green-700',
    headerBg: 'bg-green-950/95',
    inputBg: 'bg-emerald-800',
    buttonBg: 'bg-emerald-800',
    buttonHover: 'bg-emerald-700',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Glow',
    description: 'Warm evening vibes',
    background: 'bg-gradient-to-br from-orange-950 via-red-950 to-pink-900',
    cardBg: 'bg-orange-900/80',
    cardBorder: 'border-orange-800',
    textPrimary: 'text-orange-50',
    textSecondary: 'text-orange-300',
    accent: 'from-orange-600 to-red-600',
    accentHover: 'from-orange-700 to-red-700',
    headerBg: 'bg-orange-950/95',
    inputBg: 'bg-orange-800',
    buttonBg: 'bg-orange-800',
    buttonHover: 'bg-orange-700',
  },
  galaxy: {
    id: 'galaxy',
    name: 'Galaxy Dreams',
    description: 'Cosmic wonder',
    background: 'bg-gradient-to-br from-violet-950 via-purple-950 to-fuchsia-900',
    cardBg: 'bg-purple-900/80',
    cardBorder: 'border-purple-800',
    textPrimary: 'text-purple-50',
    textSecondary: 'text-purple-300',
    accent: 'from-purple-600 to-fuchsia-600',
    accentHover: 'from-purple-700 to-fuchsia-700',
    headerBg: 'bg-violet-950/95',
    inputBg: 'bg-purple-800',
    buttonBg: 'bg-purple-800',
    buttonHover: 'bg-purple-700',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyber City',
    description: 'Neon future',
    background: 'bg-gradient-to-br from-slate-950 via-blue-950 to-cyan-950',
    cardBg: 'bg-slate-900/80',
    cardBorder: 'border-cyan-700',
    textPrimary: 'text-cyan-100',
    textSecondary: 'text-cyan-400',
    accent: 'from-cyan-500 to-pink-500',
    accentHover: 'from-cyan-600 to-pink-600',
    headerBg: 'bg-slate-950/95',
    inputBg: 'bg-slate-800',
    buttonBg: 'bg-slate-800',
    buttonHover: 'bg-slate-700',
  },
  light: {
    id: 'light',
    name: 'Bright Day',
    description: 'Clean and bright',
    background: 'bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50',
    cardBg: 'bg-white/90',
    cardBorder: 'border-slate-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    accent: 'from-blue-500 to-indigo-600',
    accentHover: 'from-blue-600 to-indigo-700',
    headerBg: 'bg-white/95',
    inputBg: 'bg-slate-100',
    buttonBg: 'bg-slate-100',
    buttonHover: 'bg-slate-200',
  },
  retro: {
    id: 'retro',
    name: 'Retro Arcade',
    description: 'Pixel perfect',
    background: 'bg-gradient-to-br from-amber-950 via-yellow-950 to-orange-900',
    cardBg: 'bg-amber-900/80',
    cardBorder: 'border-yellow-700',
    textPrimary: 'text-amber-50',
    textSecondary: 'text-yellow-300',
    accent: 'from-yellow-500 to-orange-600',
    accentHover: 'from-yellow-600 to-orange-700',
    headerBg: 'bg-amber-950/95',
    inputBg: 'bg-amber-800',
    buttonBg: 'bg-amber-800',
    buttonHover: 'bg-amber-700',
  },
};
